import React from "react";
import { Text, Pressable, ScrollView, Alert } from "react-native";
import { Stack, router, useLocalSearchParams } from "expo-router";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { COLORS } from "../../constants/colors";
import * as FileSystem from "expo-file-system";

export default function ExportReport() {
  const params = useLocalSearchParams();

  // ✅ Safely extract all params
  const getParam = (val: any) => (Array.isArray(val) ? val[0] : val ?? "-");

  const totalCompleted = getParam(params.totalCompleted);
  const recog = getParam(params.recog);
  const uc = getParam(params.uc);
  const lc = getParam(params.lc);
  const draw = getParam(params.draw);
  const highestPair = getParam(params.highestPair);
  const highestAcc = getParam(params.highestAcc);
  const monster = getParam(params.monster);
  const garden = getParam(params.garden);
  const strong = getParam(params.strong);
  const weak = getParam(params.weak);
  const lowestPairs = getParam(params.lowestPairs);
  const lowestAccuracyLetters = getParam(params.lowestAccuracyLetters);

  // ✅ Generate and Save PDF directly (no preview)
  const handleGeneratePDF = async () => {
    try {
      const html = `
        <html>
          <head>
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <style>
              body { font-family: Arial, sans-serif; padding: 24px; color: #222; line-height: 1.6; }
              h1 { color: #0C2D57; margin-bottom: 6px; }
              h2 { color: #4FB6B2; margin-top: 24px; margin-bottom: 10px; }
              table { width: 100%; border-collapse: collapse; margin-top: 12px; }
              td, th { border: 1px solid #ccc; padding: 8px; }
              th { background: #E6FAF9; text-align: left; }
              ul { margin-top: 10px; }
              li { margin-bottom: 6px; }
              footer { margin-top: 24px; font-style: italic; color: #666; }
            </style>
          </head>
          <body>
            <h1>AlphaBoost AI - Letter Recognition Report</h1>
            <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>

            <h2>Summary</h2>
            <table>
              <tr><th>Letters Mastered</th><td>${totalCompleted}/26</td></tr>
              <tr><th>Average Stars</th><td>Recog ${recog}, UC ${uc}, LC ${lc}, Draw ${draw}</td></tr>
              <tr><th>Highest Confusion Accuracy</th><td>${highestPair?.toUpperCase?.() ?? "-"} – ${highestAcc}%</td></tr>
            </table>

            <h2>Game High Scores</h2>
            <table>
              <tr><th>Monster Feeding</th><td>${monster}</td></tr>
              <tr><th>Letter Garden</th><td>${garden}</td></tr>
            </table>

            <h2>Highlights</h2>
            <ul>
              <li><strong>Strongest Letters:</strong> ${strong}</li>
              <li><strong>Needs Practice:</strong> ${weak}</li>
            </ul>

            <h2>Focus & Improvement Areas</h2>
            <ul>
              <li><strong>Lowest Confusing Pairs:</strong> ${lowestPairs || "–"}</li>
              <li><strong>Lowest Accuracy Letters:</strong> ${lowestAccuracyLetters || "–"}</li>
            </ul>

            <footer>
              Generated by AlphaBoost AI Learning System
            </footer>
          </body>
        </html>
      `;

      // 🧾 Generate PDF without preview
      const { uri } = await Print.printToFileAsync({ html });

      // 📂 Rename the file to a custom name
      const newFileUri = `${FileSystem.documentDirectory}AlphaBoost_Letter_Recognition_Report.pdf`;
      await FileSystem.moveAsync({
        from: uri,
        to: newFileUri,
      });

      // 📨 Share or alert location
      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(newFileUri, {
          mimeType: "application/pdf",
          dialogTitle: "Share Letter Recognition Report",
        });
      } else {
        Alert.alert("PDF Saved", `Report saved to:\n${newFileUri}`);
      }
    } catch (error) {
      console.error(error);
      Alert.alert("Error", "Unable to generate PDF. Please try again.");
    }
  };

  // ---------- UI ----------
  return (
    <ScrollView style={{ flex: 1, backgroundColor: COLORS.bg, padding: 20 }}>
      <Stack.Screen options={{ title: "Export Report" }} />

      <Text
        style={{
          fontSize: 22,
          fontWeight: "900",
          color: COLORS.navy,
          marginBottom: 10,
        }}
      >
        📄 Export Progress Report
      </Text>

      <Text style={{ color: COLORS.text, marginBottom: 20 }}>
        Generate and save a professional PDF version of your child’s
        <Text style={{ fontWeight: "700" }}> Letter Recognition Report</Text>.
      </Text>

      <Pressable
        onPress={handleGeneratePDF}
        style={{
          backgroundColor: COLORS.teal,
          padding: 14,
          borderRadius: 10,
          alignItems: "center",
        }}
      >
        <Text style={{ color: "#fff", fontWeight: "900", fontSize: 16 }}>
          🖨️ Generate & Save PDF
        </Text>
      </Pressable>

      <Pressable
        onPress={() => router.back()}
        style={{
          marginTop: 20,
          padding: 12,
          borderRadius: 10,
          borderWidth: 1,
          borderColor: COLORS.border,
          alignItems: "center",
        }}
      >
        <Text style={{ color: COLORS.text }}>⬅️ Back to Report</Text>
      </Pressable>
    </ScrollView>
  );
}
